<div class="course_title">
        <p><b>IT 207 (Summer 2022) <br /></b> Erhan Uyar<br /> George Mason University
        </p>
    </div>
    <div class="student_contact">
        <p><b>Darya Shorish-Andish</b><br />
            <a href="https://outlook.office.com/mail/"> Email Me</a><br/>
        </p>
        <p><small><b><b>Last Modified:</b> <span id="demo">Time Date Zone</span> EST</small></b>
        </p>
    </div>