<div class="menu">
        <a href="https://helios.vse.gmu.edu/~dshorish/IT207/PractLAB/Lab0/">Assignments and Practicum</a>
        <h2>Lab Assignments</h2>
        <ul>
            <li><a href="http://helios.vse.gmu.edu/~dshorish/IT207/LAB1/">Assignment 1</a></li>
            <li><a href="http://helios.vse.gmu.edu/~dshorish/IT207/LAB2/">Assignment 2</a></li>
            <li><a href="http://helios.vse.gmu.edu/~dshorish/IT207/LAB3/">Assignment 3</a></li>
            <li><a href="http://helios.vse.gmu.edu/~dshorish/IT207/LAB4/">Assignment 4</a></li>
            <h2>Lab Practicum</h2>
            <li><a href="http://helios.vse.gmu.edu/~dshorish/IT207/LABP1/">Practicum 1</a></li>
            <li><a href="http://helios.vse.gmu.edu/~dshorish/IT207/LABP2/">Practicum 2</a></li>
        </ul>
    </div>